name: Format C++ Code using ClangFormat

on:
  push:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install ClangFormat
      run: sudo apt-get install -y clang-format
    - name: Format code
      run: |
        find . -iname '*.cpp' -o -iname '*.hpp' -o -iname '*.h' | xargs clang-format -i
    - name: Commit changes
      run: |
        git config --global user.name "Ibad Rather"
        git config --global user.email "ibad.rather.ir@gmail.com"
        git commit -am "Format C++ code"
        git push
